<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "news_exampleextension"
 *
 * Auto generated by Extension Builder 2015-03-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Additional types for EXT:news',
	'description' => 'This TYPO3 extension is an example how to extend EXT:news with new news types.',
	'category' => 'fe',
	'author' => 'Peter Kraume',
	'author_email' => 'peter.kraume@gmx.de',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2.0',
			'fluid' => '6.2.0',
			'typo3' => '6.2.0-6.2.999',
			'news' => '3.1.0-3.1.999',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>